// Package vscode generates VS Code / Cursor terminal color customization JSON.
// The output is a JSON object suitable for merging into a VS Code settings.json
// under the "workbench.colorCustomizations" key.
package vscode

import (
	"bytes"
	"text/template"

	"github.com/kylesnowschwartz/the-themer/adapter"
	"github.com/kylesnowschwartz/the-themer/palette"
)

func init() {
	adapter.Register(&vscodeAdapter{})
}

type vscodeAdapter struct{}

func (v *vscodeAdapter) Name() string                     { return "vscode" }
func (v *vscodeAdapter) DirName() string                  { return "vscode" }
func (v *vscodeAdapter) FileName(themeName string) string { return themeName + ".jsonc" }

func (v *vscodeAdapter) Generate(cfg palette.Config) ([]byte, error) {
	var buf bytes.Buffer
	if err := vscodeTmpl.Execute(&buf, cfg); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// vscodeTmpl renders VS Code / Cursor terminal color customizations.
//
// Output is a JSONC snippet meant to be merged into settings.json under
// "workbench.colorCustomizations". The ANSI color mapping follows the
// standard ANSI index order used by VS Code's terminal:
//
//	color0  = ansiBlack       color8  = ansiBrightBlack
//	color1  = ansiRed         color9  = ansiBrightRed
//	color2  = ansiGreen       color10 = ansiBrightGreen
//	color3  = ansiYellow      color11 = ansiBrightYellow
//	color4  = ansiBlue        color12 = ansiBrightBlue
//	color5  = ansiMagenta     color13 = ansiBrightMagenta
//	color6  = ansiCyan        color14 = ansiBrightCyan
//	color7  = ansiWhite       color15 = ansiBrightWhite
var vscodeTmpl = template.Must(template.New("vscode").Parse(
	`// {{.Theme.Name}} terminal theme for VS Code / Cursor
// Generated by the-themer — paste into "workbench.colorCustomizations"
{
    "terminal.background": "{{.Palette.BG}}",
    "terminal.foreground": "{{.Palette.FG}}",
    "terminal.selectionBackground": "{{.Palette.SelectionBG}}",
    "terminal.selectionForeground": "{{.Palette.SelectionFG}}",
    "terminalCursor.foreground": "{{.Palette.Cursor}}",
    "terminal.ansiBlack": "{{.Palette.Color0}}",
    "terminal.ansiRed": "{{.Palette.Color1}}",
    "terminal.ansiGreen": "{{.Palette.Color2}}",
    "terminal.ansiYellow": "{{.Palette.Color3}}",
    "terminal.ansiBlue": "{{.Palette.Color4}}",
    "terminal.ansiMagenta": "{{.Palette.Color5}}",
    "terminal.ansiCyan": "{{.Palette.Color6}}",
    "terminal.ansiWhite": "{{.Palette.Color7}}",
    "terminal.ansiBrightBlack": "{{.Palette.Color8}}",
    "terminal.ansiBrightRed": "{{.Palette.Color9}}",
    "terminal.ansiBrightGreen": "{{.Palette.Color10}}",
    "terminal.ansiBrightYellow": "{{.Palette.Color11}}",
    "terminal.ansiBrightBlue": "{{.Palette.Color12}}",
    "terminal.ansiBrightMagenta": "{{.Palette.Color13}}",
    "terminal.ansiBrightCyan": "{{.Palette.Color14}}",
    "terminal.ansiBrightWhite": "{{.Palette.Color15}}",
    "panel.background": "{{.Palette.BG}}"
}`))
