// Package vscode generates VS Code / Cursor color customization JSON.
// The output covers the full editor UI — terminal, editor, sidebar, activity bar,
// tabs, status bar, title bar, panel, inputs, lists, and scrollbar.
package vscode

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"text/template"

	"github.com/kylesnowschwartz/the-themer/adapter"
	"github.com/kylesnowschwartz/the-themer/palette"
)

func init() {
	adapter.Register(&vscodeAdapter{})
}

type vscodeAdapter struct{}

func (v *vscodeAdapter) Name() string                     { return "vscode" }
func (v *vscodeAdapter) DirName() string                  { return "vscode" }
func (v *vscodeAdapter) FileName(themeName string) string { return themeName + ".jsonc" }

func (v *vscodeAdapter) Generate(cfg palette.Config) ([]byte, error) {
	var buf bytes.Buffer
	if err := vscodeTmpl.Execute(&buf, cfg); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// adjustBrightness shifts a hex color's brightness by a factor.
// factor > 1.0 lightens, < 1.0 darkens. Clamps to 0-255.
func adjustBrightness(hex string, factor float64) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) != 6 {
		return "#" + hex
	}
	r, _ := strconv.ParseInt(hex[0:2], 16, 64)
	g, _ := strconv.ParseInt(hex[2:4], 16, 64)
	b, _ := strconv.ParseInt(hex[4:6], 16, 64)

	clamp := func(v int64) int64 {
		if v > 255 {
			return 255
		}
		if v < 0 {
			return 0
		}
		return v
	}

	r = clamp(int64(float64(r) * factor))
	g = clamp(int64(float64(g) * factor))
	b = clamp(int64(float64(b) * factor))

	return fmt.Sprintf("#%02x%02x%02x", r, g, b)
}

// withAlpha appends a hex alpha channel to a color. alpha is 0-255.
func withAlpha(hex string, alpha int) string {
	return fmt.Sprintf("%s%02x", hex, alpha)
}

var funcMap = template.FuncMap{
	"darken":  func(hex string) string { return adjustBrightness(hex, 0.7) },
	"lighten": func(hex string) string { return adjustBrightness(hex, 1.4) },
	"dim":     func(hex string) string { return adjustBrightness(hex, 0.5) },
	"alpha":   withAlpha,
}

// vscodeTmpl renders VS Code / Cursor full editor color customizations.
//
// Output is a JSONC snippet meant to be merged into settings.json under
// "workbench.colorCustomizations". Covers terminal, editor, sidebar,
// activity bar, tabs, status bar, title bar, panel, inputs, lists,
// and scrollbar.
//
// Color derivation strategy:
//   - BG: editor, sidebar, panel backgrounds
//   - darken(BG): activity bar, title bar, tab bar (darker chrome)
//   - UI.Border: all borders
//   - UI.Dimmed: muted/secondary text
//   - UI.Accent: active indicators, badges, highlights
//   - FG: primary foreground text
//   - SelectionBG: selections, active list items
var vscodeTmpl = template.Must(template.New("vscode").Funcs(funcMap).Parse(
	`// {{.Theme.Name}} theme for VS Code / Cursor
// Generated by the-themer — paste into "workbench.colorCustomizations"
{
    // ---- Terminal ----
    "terminal.background": "{{.Palette.BG}}",
    "terminal.foreground": "{{.Palette.FG}}",
    "terminal.selectionBackground": "{{.Palette.SelectionBG}}",
    "terminal.selectionForeground": "{{.Palette.SelectionFG}}",
    "terminalCursor.foreground": "{{.Palette.Cursor}}",
    "terminal.ansiBlack": "{{.Palette.Color0}}",
    "terminal.ansiRed": "{{.Palette.Color1}}",
    "terminal.ansiGreen": "{{.Palette.Color2}}",
    "terminal.ansiYellow": "{{.Palette.Color3}}",
    "terminal.ansiBlue": "{{.Palette.Color4}}",
    "terminal.ansiMagenta": "{{.Palette.Color5}}",
    "terminal.ansiCyan": "{{.Palette.Color6}}",
    "terminal.ansiWhite": "{{.Palette.Color7}}",
    "terminal.ansiBrightBlack": "{{.Palette.Color8}}",
    "terminal.ansiBrightRed": "{{.Palette.Color9}}",
    "terminal.ansiBrightGreen": "{{.Palette.Color10}}",
    "terminal.ansiBrightYellow": "{{.Palette.Color11}}",
    "terminal.ansiBrightBlue": "{{.Palette.Color12}}",
    "terminal.ansiBrightMagenta": "{{.Palette.Color13}}",
    "terminal.ansiBrightCyan": "{{.Palette.Color14}}",
    "terminal.ansiBrightWhite": "{{.Palette.Color15}}",

    // ---- Editor ----
    "editor.background": "{{.Palette.BG}}",
    "editor.foreground": "{{.Palette.FG}}",
    "editorCursor.foreground": "{{.Palette.Cursor}}",
    "editor.selectionBackground": "{{.Palette.SelectionBG}}",
    "editor.lineHighlightBackground": "{{alpha (lighten .Palette.BG) 40}}",
    "editorLineNumber.foreground": "{{.Palette.UI.Dimmed}}",
    "editorLineNumber.activeForeground": "{{.Palette.UI.Accent}}",
    "editorIndentGuide.background1": "{{alpha .Palette.UI.Border 40}}",
    "editorBracketMatch.background": "{{alpha .Palette.UI.Accent 30}}",
    "editorBracketMatch.border": "{{.Palette.UI.Accent}}",

    // ---- Sidebar ----
    "sideBar.background": "{{.Palette.BG}}",
    "sideBar.foreground": "{{.Palette.FG}}",
    "sideBar.border": "{{.Palette.UI.Border}}",
    "sideBarTitle.foreground": "{{.Palette.UI.Accent}}",
    "sideBarSectionHeader.background": "{{darken .Palette.BG}}",

    // ---- Activity Bar ----
    "activityBar.background": "{{darken .Palette.BG}}",
    "activityBar.foreground": "{{.Palette.UI.Accent}}",
    "activityBar.border": "{{.Palette.UI.Border}}",
    "activityBar.activeBorder": "{{.Palette.UI.Accent}}",
    "activityBarBadge.background": "{{.Palette.UI.Accent}}",
    "activityBarBadge.foreground": "{{.Palette.BG}}",

    // ---- Tabs ----
    "tab.activeBackground": "{{.Palette.BG}}",
    "tab.activeForeground": "{{.Palette.UI.Accent}}",
    "tab.inactiveBackground": "{{darken .Palette.BG}}",
    "tab.inactiveForeground": "{{.Palette.UI.Dimmed}}",
    "tab.activeBorderTop": "{{.Palette.UI.Accent}}",
    "tab.border": "{{.Palette.UI.Border}}",
    "editorGroupHeader.tabsBackground": "{{darken .Palette.BG}}",

    // ---- Status Bar ----
    "statusBar.background": "{{darken .Palette.BG}}",
    "statusBar.foreground": "{{.Palette.FG}}",
    "statusBar.border": "{{.Palette.UI.Border}}",
    "statusBarItem.hoverBackground": "{{alpha .Palette.UI.Accent 30}}",

    // ---- Title Bar ----
    "titleBar.activeBackground": "{{darken .Palette.BG}}",
    "titleBar.activeForeground": "{{.Palette.FG}}",
    "titleBar.inactiveBackground": "{{darken .Palette.BG}}",
    "titleBar.inactiveForeground": "{{.Palette.UI.Dimmed}}",
    "titleBar.border": "{{.Palette.UI.Border}}",

    // ---- Panel ----
    "panel.background": "{{.Palette.BG}}",
    "panel.border": "{{.Palette.UI.Border}}",
    "panelTitle.activeForeground": "{{.Palette.UI.Accent}}",
    "panelTitle.activeBorder": "{{.Palette.UI.Accent}}",
    "panelTitle.inactiveForeground": "{{.Palette.UI.Dimmed}}",

    // ---- Input Fields ----
    "input.background": "{{darken .Palette.BG}}",
    "input.foreground": "{{.Palette.FG}}",
    "input.border": "{{.Palette.UI.Border}}",
    "input.placeholderForeground": "{{.Palette.UI.Dimmed}}",
    "inputValidation.errorBorder": "{{.Palette.UI.Error}}",
    "inputValidation.warningBorder": "{{.Palette.UI.Warning}}",
    "inputValidation.infoBorder": "{{.Palette.UI.Info}}",

    // ---- Lists & Trees ----
    "list.activeSelectionBackground": "{{.Palette.SelectionBG}}",
    "list.activeSelectionForeground": "{{.Palette.FG}}",
    "list.focusBackground": "{{alpha .Palette.SelectionBG 80}}",
    "list.hoverBackground": "{{alpha .Palette.UI.Border 60}}",
    "list.highlightForeground": "{{.Palette.UI.Accent}}",

    // ---- Scrollbar ----
    "scrollbarSlider.background": "{{alpha .Palette.UI.Border 60}}",
    "scrollbarSlider.hoverBackground": "{{alpha .Palette.UI.Border 120}}",
    "scrollbarSlider.activeBackground": "{{.Palette.UI.Accent}}",

    // ---- Editor Highlights (tame yellows) ----
    "editor.findMatchBackground": "{{alpha .Palette.UI.Accent 40}}",
    "editor.findMatchHighlightBackground": "{{alpha .Palette.UI.Accent 20}}",
    "editor.wordHighlightBackground": "{{alpha .Palette.UI.Accent 20}}",
    "editor.wordHighlightStrongBackground": "{{alpha .Palette.UI.Accent 30}}",

    // ---- Badges ----
    "badge.background": "{{.Palette.UI.Accent}}",
    "badge.foreground": "{{.Palette.BG}}",

    // ---- Git Decorations ----
    "gitDecoration.modifiedResourceForeground": "{{.Palette.UI.Info}}",
    "gitDecoration.untrackedResourceForeground": "{{.Palette.UI.Success}}",
    "gitDecoration.deletedResourceForeground": "{{.Palette.UI.Error}}",
    "gitDecoration.conflictingResourceForeground": "{{.Palette.UI.Warning}}",
    "gitDecoration.ignoredResourceForeground": "{{.Palette.UI.Dimmed}}",

    // ---- Notifications ----
    "notificationCenter.border": "{{.Palette.UI.Border}}",
    "notifications.background": "{{darken .Palette.BG}}",
    "notifications.foreground": "{{.Palette.FG}}",
    "notifications.border": "{{.Palette.UI.Border}}",

    // ---- Peek View ----
    "peekView.border": "{{.Palette.UI.Accent}}",
    "peekViewEditor.background": "{{darken .Palette.BG}}",
    "peekViewResult.background": "{{darken .Palette.BG}}",
    "peekViewTitle.background": "{{darken .Palette.BG}}",
    "peekViewResult.matchHighlightBackground": "{{alpha .Palette.UI.Accent 30}}",

    // ---- Diff Editor ----
    "diffEditor.insertedTextBackground": "{{alpha .Palette.UI.Success 20}}",
    "diffEditor.removedTextBackground": "{{alpha .Palette.UI.Error 20}}"
}`))
